### ISSUE TITLE
Chrome crashes

### ISSUE THREAD

**Issue by Raghuramanvaradhan** [mmehta-10/selenium-grid-fargate#1]
Hi i am using Aws fargate as per the presentation by you. when i use 2 containers with 20 browser instances
Config : 4CPU , 16gb memory
some times i get most test cases fail because of chrome crash . I run scripts with 12 parallel currently my goal is to increase that to 60 parallel .When i search for solution sites says SHM size should be increased . How can we achieve this in fargate. and finally Chrome crashes but chrome headless succeed . kindly assist me here

**Comment by mmehta-10** [comment]
@Raghuramanvaradhan Being a serverless technology, Fargate does not support using host's shared memory. This is mentioned in ECS documentation here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html under `sharedMemorySize`


![image](https://user-images.githubusercontent.com/13069070/87393445-d3c29880-c5cb-11ea-9e12-57854be18d64.png)

As a workaround, disabling Chrome browser's use of shared memory by passing `--disable-dev-shm-usage` might help. Here's how to do it in Java -

```
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.addArguments("--disable-dev-shm-usage");
WebDriver driver = new RemoteWebDriver(new URL(<seleniumGridUrl>), chromeOptions);
driver.get("http://www.google.com");
driver.quit();
```

**Comment by Raghuramanvaradhan** [comment]
Thanks done !
